name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for branch 1 and on start directory, command.txt file changes or by manually running the workflow from actions tab
on:
  workflow_dispatch:

env: # Or as an environment variable
  user: ${{ secrets.USER }}
  key: ${{ secrets.KEY }}   
  recovery: ${{ secrets.RECOVERY }}   
  tempdir: ${{ runner.temp }}

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Get cache directory for npm
        id: cache-dir
        shell: bash
        run: echo "::set-output name=npmcache::$(npm config get cache)"

      - name: Trying to use the old cache if available
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache-dir.outputs.npmcache }}
          key: ${{ runner.os }}-cache-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-
            ${{ runner.os }}-

      - name: clone
        shell: bash
        run: |
          REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git clone $REPO .              

      - name: download part
        shell: cmd
        run: |
          choco install ffmpeg wget
          wget https://github.com/fawazahmed0/quran-videos/releases/download/v0.0.1/subtitles.zip
          wget https://github.com/fawazahmed0/quran-videos/releases/download/v0.0.1/pixabay.videos.zip
          wget https://github.com/fawazahmed0/audio-ayah-arabic-1/releases/download/v1.4/my-artifact.zip
      - name: zip extract
        shell: cmd
        run: |
          7z x subtitles.zip
          7z x pixabay.videos.zip
          7z x my-artifact.zip
      - name: node part  
        run: |
          npm install
          node hardcodesub.js

      # commiting and pushing changes
      - name: commit and push
        if: ${{ always() }}
        shell: bash
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git pull
          git add -A
          git commit -m 'Add uploaded links'
          git push

