name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for branch 1 and on start directory, command.txt file changes or by manually running the workflow from actions tab
on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

  workflow_dispatch:

env: # Or as an environment variable
  user: ${{ secrets.USER }}
  key: ${{ secrets.KEY }}   

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Get cache directory for npm
        id: cache-dir
        shell: bash
        run: echo "::set-output name=npmcache::$(npm config get cache)"

      - name: Trying to use the old cache if available
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache-dir.outputs.npmcache }}
          key: ${{ runner.os }}-cache-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-
            ${{ runner.os }}-

      - uses: actions/checkout@v2
      - name: download part
        shell: cmd
        run: |
      #    choco install ffmpeg wget
      #    wget https://github.com/fawazahmed0/quran-videos/releases/download/v0.0.1/subtitles.zip
      #    wget https://github.com/fawazahmed0/quran-videos/releases/download/v0.0.1/pixabay.videos.zip
      #    wget https://github.com/fawazahmed0/audio-ayah-arabic-1/releases/download/v1.4/my-artifact.zip
      - name: zip extract
        shell: cmd
        run: |
          dir
      #    7z x subtitles.zip
      #    7z x pixabay.videos.zip
      #    7z x my-artifact.zip
      - name: node part  
        run: |
          npm install
          node hardcodesub.js

      - name: Saving the log.txt as artifcat
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: log
          path: example.png    
      # commiting and pushing changes
      - name: commit and push
        shell: cmd
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git pull
          git add -A
          git commit -m 'Add uploaded links'
          git push

